from auth import authenticator
import streamlit as st
import pandas as pd
import numpy as np
import io

st.set_page_config(page_title="Data Analyst AI Agent", layout="wide", page_icon="📊")

from agent import ask_agent
from database import conn, cursor

name, authentication_status, username = authenticator.login("Login", "main")

if authentication_status:
    authenticator.logout("Logout", "sidebar")
    st.sidebar.success(f"👋 Welcome, {name}")

    if username == "admin":
        st.sidebar.info("🛡️ Role: Admin")
        st.sidebar.markdown("---")
        if st.sidebar.button("📋 View all query history"):
            rows = cursor.execute(
                "SELECT username, filename, query, created_at FROM history ORDER BY created_at DESC LIMIT 50"
            ).fetchall()
            if rows:
                st.subheader("📋 All Query History (Admin)")
                st.dataframe(pd.DataFrame(rows, columns=["User","File","Query","Time"]), use_container_width=True)
            else:
                st.info("No queries yet.")
    else:
        st.sidebar.info("👤 Role: User")

    st.title("📊 Data Analyst AI Agent")
    st.caption("Upload any dataset · Ask questions in plain English · Get AI insights + charts + PDF reports")

    # PDF setup
    try:
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.pagesizes import letter
        from xml.sax.saxutils import escape
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        PDF_AVAILABLE = True
    except ImportError:
        PDF_AVAILABLE = False

    def generate_pdf(df, result_text, chart_path=None):
        if not PDF_AVAILABLE:
            return None
        doc = SimpleDocTemplate("report.pdf", pagesize=letter)
        styles = getSampleStyleSheet()
        content = []
        content.append(Paragraph("Data Analysis Report", styles["Title"]))
        content.append(Spacer(1, 12))
        content.append(Paragraph("Generated by Data Analyst AI Agent", styles["Italic"]))
        content.append(Spacer(1, 20))
        content.append(Paragraph("<b>Dataset Summary:</b>", styles["Heading2"]))
        content.append(Spacer(1, 6))
        content.append(Paragraph(f"Rows: {df.shape[0]} | Columns: {df.shape[1]} | Missing values: {df.isnull().sum().sum()}", styles["Normal"]))
        content.append(Spacer(1, 20))
        content.append(Paragraph("<b>AI Analysis Result:</b>", styles["Heading2"]))
        content.append(Spacer(1, 10))
        for line in escape(str(result_text)).split("\n"):
            content.append(Paragraph(line or " ", styles["Normal"]))
            content.append(Spacer(1, 4))
        if chart_path:
            content.append(Spacer(1, 20))
            content.append(Paragraph("<b>Visualization:</b>", styles["Heading2"]))
            content.append(Spacer(1, 10))
            content.append(RLImage(chart_path, width=400, height=250))
        content.append(Spacer(1, 20))
        content.append(Paragraph("Report generated automatically by Data Analyst AI Agent.", styles["Italic"]))
        doc.build(content)
        return "report.pdf"

    # ── File upload ──────────────────────────────────────────────────────────
    uploaded_file = st.file_uploader(
        "📁 Upload your dataset",
        type=["csv", "xlsx", "xls"],
        help="Supports CSV and Excel files up to 50MB"
    )

    if uploaded_file:
        # Load file
        try:
            if uploaded_file.name.endswith(".csv"):
                df = pd.read_csv(uploaded_file)
            else:
                df = pd.read_excel(uploaded_file)
        except Exception as e:
            st.error(f"❌ Could not read file: {e}")
            st.stop()

        # Sidebar filters
        st.sidebar.markdown("---")
        st.sidebar.header("🔍 Filter Data")
        obj_cols = df.select_dtypes(include='object').columns.tolist()
        for col in obj_cols[:4]:
            unique_vals = df[col].dropna().unique().tolist()
            if len(unique_vals) <= 30:
                selected = st.sidebar.multiselect(f"{col}", unique_vals)
                if selected:
                    df = df[df[col].isin(selected)]

        # Sidebar export
        st.sidebar.markdown("---")
        csv_bytes = df.to_csv(index=False).encode()
        st.sidebar.download_button(
            label="⬇️ Export filtered CSV",
            data=csv_bytes,
            file_name=f"filtered_{uploaded_file.name.replace('.xlsx','').replace('.xls','')}.csv",
            mime="text/csv"
        )

        num_cols = df.select_dtypes(include='number').columns.tolist()

        # ── Tabs ─────────────────────────────────────────────────────────────
        tab1, tab2, tab3, tab4, tab5 = st.tabs([
            "📄 Preview", "🔎 Data Quality", "📊 Charts", "💬 Ask AI", "📋 History"
        ])

        # ── TAB 1: Preview ────────────────────────────────────────────────────
        with tab1:
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Rows", f"{df.shape[0]:,}")
            col2.metric("Columns", df.shape[1])
            col3.metric("Missing values", f"{df.isnull().sum().sum():,}")
            col4.metric("Numeric columns", len(num_cols))

            st.subheader("Data preview")
            st.dataframe(df.head(50), use_container_width=True)

            if num_cols:
                st.subheader("Statistical summary")
                st.dataframe(df[num_cols].describe().round(2), use_container_width=True)

        # ── TAB 2: Data Quality ───────────────────────────────────────────────
        with tab2:
            st.subheader("Data quality report")

            # Missing values
            missing = df.isnull().sum()
            missing_pct = (missing / len(df) * 100).round(1)
            missing_df = pd.DataFrame({
                "Column": missing.index,
                "Missing count": missing.values,
                "Missing %": missing_pct.values,
                "Data type": df.dtypes.values.astype(str)
            }).sort_values("Missing count", ascending=False)

            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**Missing values by column**")
                st.dataframe(missing_df, use_container_width=True, hide_index=True)
            with col2:
                st.markdown("**Column data types**")
                dtype_counts = df.dtypes.astype(str).value_counts().reset_index()
                dtype_counts.columns = ["Type", "Count"]
                st.dataframe(dtype_counts, use_container_width=True, hide_index=True)

                st.markdown("**Duplicate rows**")
                dupes = df.duplicated().sum()
                if dupes == 0:
                    st.success(f"✅ No duplicate rows found")
                else:
                    st.warning(f"⚠️ {dupes} duplicate rows detected")
                    if st.button("Remove duplicates"):
                        df = df.drop_duplicates()
                        st.success(f"✅ Removed {dupes} duplicate rows")

            # Unique value counts for object columns
            if obj_cols:
                st.markdown("**Unique values per text column**")
                uniq = pd.DataFrame({
                    "Column": obj_cols,
                    "Unique values": [df[c].nunique() for c in obj_cols],
                    "Sample values": [", ".join(df[c].dropna().astype(str).unique()[:3].tolist()) for c in obj_cols]
                })
                st.dataframe(uniq, use_container_width=True, hide_index=True)

        # ── TAB 3: Charts ─────────────────────────────────────────────────────
        with tab3:
            st.subheader("Interactive chart builder")

            if not num_cols:
                st.info("No numeric columns found for charting.")
            else:
                col1, col2, col3 = st.columns(3)
                with col1:
                    chart_type = st.selectbox("Chart type", ["Bar", "Line", "Area", "Scatter", "Histogram", "Pie"])
                with col2:
                    x_col = st.selectbox("X axis", df.columns.tolist())
                with col3:
                    y_col = st.selectbox("Y axis", num_cols)

                if chart_type == "Bar":
                    if x_col == y_col:
                       st.warning("Please select different columns for X and Y axis.")
                    else:
                        try:
                            chart_data = df.groupby(x_col)[y_col].sum()
                            st.bar_chart(chart_data)
                        except Exception as e:
                            st.error(f"Could not create chart: {e}")
with tab3:
    st.subheader("Interactive chart builder")
    if not num_cols:
        st.info("No numeric columns found for charting.")
    else:
        col1, col2, col3 = st.columns(3)
        with col1:
            chart_type = st.selectbox("Chart type", ["Bar","Line","Area","Histogram","Pie"])
        with col2:
            x_col = st.selectbox("X axis / Group by", df.columns.tolist())
        with col3:
            y_col = st.selectbox("Y axis (numeric)", num_cols)

        try:
            if chart_type == "Bar":
                if x_col != y_col:
                    st.bar_chart(df.groupby(x_col)[y_col].sum())
                else:
                    st.bar_chart(df[y_col])
            elif chart_type == "Line":
                st.line_chart(df[y_col])
            elif chart_type == "Area":
                st.area_chart(df[y_col])
            elif chart_type == "Histogram":
                import plotly.express as px
                fig = px.histogram(df, x=y_col, nbins=30, color_discrete_sequence=["#185FA5"])
                st.plotly_chart(fig, use_container_width=True)
            elif chart_type == "Pie":
                if x_col != y_col:
                    pie_data = df.groupby(x_col)[y_col].sum().reset_index().head(10)
                    import plotly.express as px
                    fig = px.pie(pie_data, names=x_col, values=y_col)
                    st.plotly_chart(fig, use_container_width=True)
                else:
                    st.warning("Select different X and Y columns for Pie chart.")
        except Exception as e:
            st.error(f"Chart error: {e}")

        # ── TAB 4: Ask AI ─────────────────────────────────────────────────────
        with tab4:
            st.subheader("Ask AI about your data")

            # Suggested questions based on columns
            st.markdown("**💡 Suggested questions — click to use:**")
            suggestions = []
            if num_cols:
                suggestions.append(f"What is the average {num_cols[0]}?")
                suggestions.append(f"Which rows have the highest {num_cols[0]}?")
            if obj_cols:
                suggestions.append(f"How many unique values are in {obj_cols[0]}?")
                if num_cols:
                    suggestions.append(f"What is the total {num_cols[0]} by {obj_cols[0]}?")
            suggestions.append("Are there any anomalies or outliers in this dataset?")
            suggestions.append("Give me a summary of insights from this data")

            cols = st.columns(3)
            clicked = None
            for i, s in enumerate(suggestions[:6]):
                if cols[i % 3].button(s, key=f"sug_{i}", use_container_width=True):
                    clicked = s

            st.markdown("---")
            query = st.text_input(
                "Or type your own question:",
                value=clicked or "",
                placeholder="e.g. What are the top 5 products by revenue?"
            )

            if query:
                with st.spinner("🤖 AI is analyzing your data..."):
                    result = ask_agent(df, query)

                cursor.execute(
                    "INSERT INTO history (username, filename, query) VALUES (?, ?, ?)",
                    (username, uploaded_file.name, query)
                )
                conn.commit()

                st.subheader("📊 AI Analysis")
                st.markdown(result)

                # Auto chart if query mentions visualization
                if any(w in query.lower() for w in ["chart","plot","graph","visualize","show me","bar","line","pie"]):
                    if num_cols:
                        st.subheader("📈 Auto-generated chart")
                        chart_data = df[num_cols[:3]]
                        st.bar_chart(chart_data)

                # PDF download
                chart_path = None
                if PDF_AVAILABLE and num_cols:
                    try:
                        import matplotlib
                        matplotlib.use('Agg')
                        import matplotlib.pyplot as plt
                        plt.figure(figsize=(8, 4))
                        df[num_cols[:3]].sum().plot(kind='bar', color='#185FA5')
                        plt.title("Summary Chart")
                        plt.tight_layout()
                        chart_path = "chart.png"
                        plt.savefig(chart_path)
                        plt.close()
                    except Exception:
                        chart_path = None

                if PDF_AVAILABLE:
                    pdf_file = generate_pdf(df, result, chart_path)
                    if pdf_file:
                        with open(pdf_file, "rb") as f:
                            st.download_button(
                                label="📄 Download PDF report",
                                data=f,
                                file_name="analysis_report.pdf",
                                mime="application/pdf"
                            )

        # ── TAB 5: History ────────────────────────────────────────────────────
    with tab5:
        st.subheader("Your query history")

        try:
            rows = cursor.execute(
                "SELECT filename, query, created_at FROM history WHERE username=? ORDER BY created_at DESC LIMIT 30",
                (username,)
            ).fetchall()

        if rows:
                hist_df = pd.DataFrame(
                    rows,
                    columns=["File", "Query", "Time"]
                )
                st.dataframe(
                    hist_df,
                    use_container_width=True,
                    hide_index=True
                    )
            else:
                st.info(
                    "No queries yet. Ask your first question in the Ask AI tab!"
                )

        except Exception as e:
            st.error(f"Could not load history: {e}")

    else:
        # Landing state
        st.markdown("---")
        col1, col2, col3 = st.columns(3)
        col1.info("**Step 1**\n\n📁 Upload a CSV or Excel file above")
        col2.info("**Step 2**\n\n💬 Ask any question about your data in plain English")
        col3.info("**Step 3**\n\n📄 Download the AI-generated PDF report")

        st.markdown("---")
        st.markdown("**💡 Example questions you can ask:**")
        examples = [
            "What is the average sales by region?",
            "Show me the top 10 customers by revenue",
            "Are there any missing values in this dataset?",
            "Plot a bar chart of monthly revenue",
            "What are the key insights from this data?",
            "Which product has the highest profit margin?"
        ]
        cols = st.columns(3)
        for i, ex in enumerate(examples):
            cols[i % 3].markdown(f"• *{ex}*")
