from auth import authenticator
import streamlit as st
import pandas as pd

from agent import ask_agent
from database import conn, cursor

name, authentication_status, username = authenticator.login(
    "Login",
    "main"
)

if authentication_status:
    authenticator.logout("Logout", "sidebar")

    st.sidebar.success(f"Welcome {name}")

    if username == "admin":
        st.sidebar.info("Role: Admin")

    elif username == "user":
        st.sidebar.info("Role: User")

    st.set_page_config(page_title="Data Analyst AI Agent", layout="wide")

    st.title("📊 Data Analyst AI Agent (Free Version)")

    st.success("🤖 AI Agent Ready! Ask anything about your data")

    uploaded_file = st.file_uploader("Upload your CSV", type=["csv"])

# PDF + Chart libraries
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.pagesizes import letter
    from xml.sax.saxutils import escape
    import matplotlib.pyplot as plt

# 📄 PDF Generator
    def generate_pdf(df, result_text):
        doc = SimpleDocTemplate("report.pdf", pagesize=letter)
        styles = getSampleStyleSheet()
        content = []

    # Title
        content.append(Paragraph("Data Analysis Report", styles["Title"]))
        content.append(Spacer(1, 12))

        content.append(Paragraph("Generated by Data Analyst AI Agent", styles["Italic"]))
        content.append(Spacer(1, 20))

    # Result section
        content.append(Paragraph("<b>Analysis Result:</b>", styles["Heading2"]))
        content.append(Spacer(1, 10))

        text = escape(str(result_text))
        lines = text.split("\n")

        for line in lines:
            content.append(Paragraph(line, styles["Normal"]))
            content.append(Spacer(1, 6))

        content.append(Spacer(1, 20))

    # Chart
        numeric_cols = df.select_dtypes(include='number').columns

        if len(numeric_cols) > 0:
            plt.figure()
            df[numeric_cols].sum().plot(kind='bar')
            plt.title("Summary Chart")

            chart_path = "chart.png"
            plt.savefig(chart_path)
            plt.close()

            content.append(Paragraph("<b>Visualization:</b>", styles["Heading2"]))
            content.append(Spacer(1, 10))

            content.append(Image(chart_path, width=400, height=250))

        content.append(Spacer(1, 20))

        content.append(Paragraph("Report generated automatically.", styles["Italic"]))

        doc.build(content)

        return "report.pdf"


    if uploaded_file:
        df = pd.read_csv(uploaded_file)

    # Filters
        st.sidebar.header("🔍 Filter Data")

        for col in df.select_dtypes(include='object').columns:
            selected = st.sidebar.multiselect(f"Filter by {col}", df[col].unique())

            if selected:
                df = df[df[col].isin(selected)]

    # Preview
        st.subheader("📄 Data Preview")
        st.dataframe(df.head())

    # Dashboard
        st.subheader("📊 Dashboard")

        numeric_cols = df.select_dtypes(include='number').columns

        if len(numeric_cols) > 0:
            st.line_chart(df[numeric_cols])
            st.bar_chart(df[numeric_cols])

    # Query
        st.subheader("💬 Ask Questions")
        query = st.text_input("Ask your data:")

        if query:
            result = ask_agent(df, query)
            cursor.execute(
                "INSERT INTO history (username, filename, query) VALUES (?, ?, ?)",
                (username, uploaded_file.name, query)
            )

            conn.commit()

            st.subheader("📊 Result")
            st.code(result)

        # Auto chart
            if "chart" in query or "plot" in query:
                if len(numeric_cols) > 0:
                    st.subheader("📊 Generated Chart")
                    st.bar_chart(df[numeric_cols])

        # PDF
            pdf_file = generate_pdf(df, result)

            with open(pdf_file, "rb") as f:
                st.download_button(
                    label="📄 Download Report",
                    data=f,
                    file_name="report.pdf"
                )