from auth import authenticator
import streamlit as st
import pandas as pd
from agent import ask_agent
from database import conn, cursor

st.set_page_config(page_title="Data Analyst AI Agent", layout="wide", page_icon="📊")

name, authentication_status, username = authenticator.login("Login", "main")

if authentication_status:
    authenticator.logout("Logout", "sidebar")
    st.sidebar.success(f"👋 Welcome, {name}")

    if username == "admin":
        st.sidebar.info("🛡️ Role: Admin")
        # Admin: show query history
        st.sidebar.markdown("---")
        if st.sidebar.button("📋 View query history"):
            rows = cursor.execute("SELECT username, filename, query, created_at FROM history ORDER BY created_at DESC LIMIT 20").fetchall()
            if rows:
                hist_df = pd.DataFrame(rows, columns=["User","File","Query","Time"])
                st.subheader("📋 Query History (Admin)")
                st.dataframe(hist_df, use_container_width=True)
            else:
                st.info("No queries yet.")
    else:
        st.sidebar.info("👤 Role: User")

    st.title("📊 Data Analyst AI Agent")
    st.success("🤖 AI Agent Ready! Upload a CSV and ask anything about your data.")

    # PDF + Chart libraries
    try:
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.pagesizes import letter
        from xml.sax.saxutils import escape
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        PDF_AVAILABLE = True
    except ImportError:
        PDF_AVAILABLE = False

    def generate_pdf(df, result_text):
        if not PDF_AVAILABLE:
            return None
        doc = SimpleDocTemplate("report.pdf", pagesize=letter)
        styles = getSampleStyleSheet()
        content = []
        content.append(Paragraph("Data Analysis Report", styles["Title"]))
        content.append(Spacer(1, 12))
        content.append(Paragraph("Generated by Data Analyst AI Agent", styles["Italic"]))
        content.append(Spacer(1, 20))
        content.append(Paragraph("<b>Analysis Result:</b>", styles["Heading2"]))
        content.append(Spacer(1, 10))
        text = escape(str(result_text))
        for line in text.split("\n"):
            content.append(Paragraph(line or " ", styles["Normal"]))
            content.append(Spacer(1, 6))
        content.append(Spacer(1, 20))
        numeric_cols = df.select_dtypes(include='number').columns
        if len(numeric_cols) > 0:
            plt.figure(figsize=(8, 4))
            df[numeric_cols].sum().plot(kind='bar', color='#185FA5')
            plt.title("Summary Chart")
            plt.tight_layout()
            chart_path = "chart.png"
            plt.savefig(chart_path)
            plt.close()
            content.append(Paragraph("<b>Visualization:</b>", styles["Heading2"]))
            content.append(Spacer(1, 10))
            content.append(Image(chart_path, width=400, height=250))
        content.append(Spacer(1, 20))
        content.append(Paragraph("Report generated automatically.", styles["Italic"]))
        doc.build(content)
        return "report.pdf"

    # File upload
    uploaded_file = st.file_uploader("📁 Upload your CSV or Excel file", type=["csv", "xlsx", "xls"])

    if uploaded_file:
        # Load file
        if uploaded_file.name.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_excel(uploaded_file)

        # Filters
        st.sidebar.header("🔍 Filter Data")
        for col in df.select_dtypes(include='object').columns[:5]:
            selected = st.sidebar.multiselect(f"Filter by {col}", df[col].unique())
            if selected:
                df = df[df[col].isin(selected)]

        # Tabs
        tab1, tab2, tab3, tab4 = st.tabs(["📄 Preview", "📊 Dashboard", "💬 Ask AI", "📋 History"])

        with tab1:
            st.subheader("Data Preview")
            col1, col2, col3 = st.columns(3)
            col1.metric("Rows", df.shape[0])
            col2.metric("Columns", df.shape[1])
            col3.metric("Missing values", df.isnull().sum().sum())
            st.dataframe(df, use_container_width=True)
            st.subheader("Statistical Summary")
            st.dataframe(df.describe(), use_container_width=True)

        with tab2:
            st.subheader("Auto Dashboard")
            numeric_cols = df.select_dtypes(include='number').columns
            if len(numeric_cols) > 0:
                col1, col2 = st.columns(2)
                with col1:
                    st.markdown("**Line Chart**")
                    st.line_chart(df[numeric_cols])
                with col2:
                    st.markdown("**Bar Chart**")
                    st.bar_chart(df[numeric_cols])
            else:
                st.info("No numeric columns found for charts.")

        with tab3:
            st.subheader("Ask AI about your data")
            query = st.text_input("💬 Type your question:", placeholder="e.g. What are the top 5 values by sales?")

            if query:
                with st.spinner("🤖 AI is analyzing your data..."):
                    result = ask_agent(df, query)

                cursor.execute(
                    "INSERT INTO history (username, filename, query) VALUES (?, ?, ?)",
                    (username, uploaded_file.name, query)
                )
                conn.commit()

                st.subheader("📊 AI Analysis Result")
                st.markdown(result)

                if any(word in query.lower() for word in ["chart", "plot", "graph", "visualize"]):
                    if len(numeric_cols) > 0:
                        st.subheader("📊 Generated Chart")
                        st.bar_chart(df[numeric_cols])

                if PDF_AVAILABLE:
                    pdf_file = generate_pdf(df, result)
                    if pdf_file:
                        with open(pdf_file, "rb") as f:
                            st.download_button(
                                label="📄 Download PDF Report",
                                data=f,
                                file_name="analysis_report.pdf",
                                mime="application/pdf"
                            )

        with tab4:
            st.subheader("Your Query History")
            rows = cursor.execute(
                "SELECT filename, query, FROM history WHERE username=?LIMIT 20",
                (username,)
            ).fetchall()
            if rows:
                hist_df = pd.DataFrame(rows, columns=["File", "Query"])
                st.dataframe(hist_df, use_container_width=True)
            else:
                st.info("No queries yet. Ask your first question above!")

    else:
        # Landing state
        st.markdown("""
        ### How to use:
        1. 📁 **Upload** a CSV or Excel file above
        2. 🔍 **Filter** data using the sidebar options  
        3. 💬 **Ask** any question about your data in plain English
        4. 📄 **Download** the AI-generated PDF report
        """)

        st.info("💡 Example questions: *'What is the average sales by region?'* · *'Show me the top 5 customers'* · *'Plot a chart of monthly revenue'*")
